baseURL = 'https://liujunguang.github.io/'
languageCode = 'en-us'
title = 'Liu Junguang'
theme = 'PaperMod'
# æ·»åŠ ä¸­æ–‡æ”¯æŒï¼Œå¦åˆ™å­—æ•°ç»Ÿè®¡ä¸å‡†
hasCJKLanguage = true

# ä»¥ä¸‹æ˜¯å®˜æ–¹æ–‡æ¡£ä¸­è´´å‡ºæ¥çš„é…ç½®
# ====================
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
# to enable google analytics, opengraph, twitter-cards and schema.
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "åˆ˜ä¿Šå…‰"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
# ä¼šæ˜¾ç¤º twitter ç­‰ç­‰å›½å†…æ— æ³•åˆ†äº«çš„å¤šä¸ªå›¾æ ‡
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
#text = "<title>"
#icon = "/apple-touch-icon.png"
#iconHeight = 35

[params.profileMode]
# needs to be explicitly set
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Tec BlogğŸ‘‹"
Content = """æˆ‘è§‰å¾—ç§˜å¯†è‡³å°‘åˆ†ä¸ºä¸¤ç§\n
ä¸€ç§æ˜¯è®¤çŸ¥è¾¾åˆ°çš„ï¼Œåˆ«äººéšç’äº†é‡è¦ä¿¡æ¯å¯¼è‡´æ— çŸ¥\n
ä¸€ç§æ˜¯ä¹ ä»¥ä¸ºå¸¸çš„ï¼Œåƒç©ºæ°”ä¸€æ ·è¢«äººä»¬å¿½è§†"""

# todo: wechat å…¬ä¼—å·
#[[params.socialIcons]]
#name = "twitter"
#url = "https://twitter.com/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Liujunguang/"

[[params.socialIcons]]
name = "zhihu"
url = "https://www.zhihu.com/people/hu-xi-1-93"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
# hide everywhere but not in structured data
hidden = true
# hide on list pages and home
hiddenInList = true
# hide on single page
hiddenInSingle = true

[params.editPost]
#URL = "https://github.com/<path_to_repo>/content"
# edit text
#Text = "Suggest Changes"
# to append file path to Edit link
#appendFilePath = true

# for search
# https://fusejs.io/api/options.html
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[params.artalk]
server = 'https://ljg.cool/artalk'
site = 'https://liujunguang.github.io/'

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "wiki"
name = "WiKi"
url = "https://github.com/Liujunguang/liujunguang.github.io/wiki"
weight = 30

[markup.highlight]
noClasses = false
#anchorLineNos = true
#codeFences = true
#guessSyntax = true
#lineNos = true
#style = "monokai"

[markup.goldmark.renderer]
# https://gohugo.io/getting-started/configuration-markup/#configure-markup
# hugo æ‰èƒ½æŒ‰é¢„æœŸæ˜¾ç¤ºæ¢è¡Œ
hardWraps = true
